version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=authdb

  postgres:
    image: postgres:14.8
    container_name: postgresql
    volumes:
      - ./postgres-script.sql:/docker-entrypoint-initdb.d/postgres-script.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gqNFG_n2dWDcL5_
      - POSTGRES_DB=financedb
    ports:
      - 5432:5432